#ifndef UNOCOMPOSITEVIDEO_H_
#define UNOCOMPOSITEVIDEO_H_

#define BYTES_PER_RASTER 46
#define PIXELS_PER_CHARACTER 9
#define CHARACTER_ROWS 29

#define LEFT_EDGE 116
#define TOP_EDGE 32
#define BOTTOM_EDGE (TOP_EDGE + CHARACTER_ROWS * PIXELS_PER_CHARACTER - 1)

#endif 
